# Generated by Django 5.2.6 on 2025-09-25 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#22c55e', help_text='Color en formato hexadecimal', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.role'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tecnologias', models.TextField(blank=True, help_text='Tecnologías separadas por comas')),
                ('url_publica', models.URLField(blank=True, help_text='URL pública del proyecto')),
                ('url_repositorio', models.URLField(blank=True, help_text='URL del repositorio de código')),
                ('is_public', models.BooleanField(default=False, help_text='¿El proyecto es visible públicamente?')),
                ('is_featured', models.BooleanField(default=False, help_text='¿Es un proyecto destacado?')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.category')),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='proyectos_colaborando', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'is_public'], name='usuarios_pr_estado_426882_idx'), models.Index(fields=['fecha_creacion'], name='usuarios_pr_fecha_c_8dcfbb_idx'), models.Index(fields=['categoria'], name='usuarios_pr_categor_be2fbf_idx')],
            },
        ),
    ]
